In [ ]:
!pip install sklearn
!pip install pandas
!pip install tensorflow
!pip install matplotlib

In [1]:
import numpy as np
import pandas as pd
import os
import tensorflow as tf
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# read iris.csv file using pandas
iris_data = pd.read_csv('iris.csv')

# read the head of csv and print
iris_data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
# Here label is 'Species' column and features are all the other columns
# Convert 'Species' column to numeric value

# Use label encoder function using sklearn
from sklearn import preprocessing

# Use instance of LabelEncoder
label_encoder = preprocessing.LabelEncoder()

# fit_transform function helps in transforming string labels to numerics
iris_data['Species'] = label_encoder.fit_transform(iris_data['Species'])

# Convert iris_data to numpy array
iris_data = iris_data.to_numpy()


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [6]:

# Seperate labels and features
x_data = iris_data[:,:4]
y_data = iris_data[:,4]

print("\nFeatures before scaling :\n----------------------")
print(x_data[:5,:])
print("\nLabels before scaling :\n------------------------")
print(y_data[:5])


Features before scaling :
----------------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Labels before scaling :
------------------------
[0. 0. 0. 0. 0.]
